name: CII

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable Virtual Machine Platform and WSL
      run: |
        dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
        dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
        wsl --set-default-version 2

    - name: Download Docker Desktop Installer
      run: Invoke-WebRequest -Uri "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe" -OutFile "DockerDesktopInstaller.exe"

    - name: Install Docker Desktop
      run: .\DockerDesktopInstaller.exe /quiet /norestart

    - name: Download ZeroTier Installer
      run: Invoke-WebRequest -Uri "https://download.zerotier.com/dist/ZeroTier%20One.msi" -OutFile "ZeroTierOne.msi"

    - name: Install ZeroTier
      run: msiexec /i ZeroTierOne.msi /quiet /norestart

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Join ZeroTier Network
      run: "C:\Program Files (x86)\ZeroTier\One\zerotier-cli.exe" join 856127940cb15a86

    - name: Check ZeroTier Networks
      run: "C:\Program Files (x86)\ZeroTier\One\zerotier-cli.exe" listnetworks
