name: CII

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable Virtual Machine Platform and WSL
      run: |
        dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
        dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
        wsl --set-default-version 2

    - name: Download Docker Desktop Installer
      run: Invoke-WebRequest -Uri "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe" -OutFile "DockerDesktopInstaller.exe"

    - name: Install Docker Desktop
      run: .\DockerDesktopInstaller.exe /quiet /norestart

    - name: Download OpenVPN
      run: Invoke-WebRequest https://github.com/OpenVPN/openvpn/releases/download/v2.5.3/openvpn-install-2.5.3-I601-Win64.exe -OutFile openvpn-installer.exe

    - name: Install OpenVPN
      run: .\openvpn-installer.exe /quiet /norestart

    - name: Authenticate OpenVPN
      run: |
        # Copy your .ovpn config to the expected location
        Copy-Item -Path kangwifi.first.ovpn -Destination "C:\Program Files\OpenVPN\config\kangwifi.first.ovpn"

    - name: Connect to VPN
      run: Start-Process -FilePath "C:\Program Files\OpenVPN\bin\openvpn.exe" -ArgumentList "--config", "C:\Program Files\OpenVPN\config\kangwifi.first.ovpn" -NoNewWindow -Wait

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: OpenVPN Tunnel Established
      run: echo "OpenVPN Tunnel has been successfully established."
