name: kangwifi-android-vnc

on: [workflow_dispatch]

jobs:
  run-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Ngrok
      run: |
        wget -q -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok.zip
        chmod +x ngrok
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ./ngrok tcp 6080 > ngrok.log 2>&1 &

    - name: Pull Docker Android Image
      run: docker pull butomo1989/docker-android-x86-9.0

    - name: Run Android Docker Container
      run: |
        docker run --privileged -d \
          -e DEVICE="Samsung Galaxy S10" \
          -e WEB_VNC=true \
          -p 6080:6080 \
          --name kangwifi-android \
          butomo1989/docker-android-x86-9.0

    - name: Print Ngrok VNC Address
      run: |
        sleep 15
        curl -s http://localhost:4040/api/tunnels | grep -o 'tcp://[^"]*' || echo "Waiting for ngrok..."

    - name: Keep job alive (infinite loop)
      run: |
        echo "Android is running via VNC. Job will stay alive..."
        tail -f /dev/null
