name: kangwifi-android13

on: [push, workflow_dispatch]

jobs:
  android-vnc:
    runs-on: ubuntu-latest
    name: Start Android 13 with VNC Access

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-x86 unzip wget curl

    - name: Download Android x86 ISO (Android 13 unofficial)
      run: |
        mkdir iso && cd iso
        wget -O android13.iso https://mirror.opensuse.org/repositories/home:/deadpoint:/android-x86_64/iso/android-x86_64-13.1-r1.iso

    - name: Create VNC password
      run: |
        mkdir -p ~/.vnc
        echo "Wifi.id123" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd

    - name: Start Android 13 with QEMU + VNC
      run: |
        nohup qemu-system-x86_64 \
          -enable-kvm \
          -m 2048 \
          -smp 2 \
          -cpu host \
          -vga virtio \
          -device virtio-tablet \
          -boot d \
          -cdrom iso/android13.iso \
          -net nic -net user \
          -name kangwifi-android13 \
          -display vnc=:1 \
          -no-reboot \
          -usbdevice tablet > qemu.log 2>&1 &

    - name: Download and Start Ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ./ngrok tcp 5901 > ngrok.log 2>&1 &

    - name: Wait & Show Ngrok VNC Address
      run: |
        sleep 20
        curl -s http://127.0.0.1:4040/api/tunnels | grep -o 'tcp://[^"]*' || echo "Ngrok tunnel not found"
