name: kangwifi-android-vnc

on: [workflow_dispatch]

jobs:
  run-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Ngrok
      run: |
        curl -s -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok.zip
        chmod +x ngrok
        sudo mv ngrok /usr/local/bin/

    - name: Authenticate Ngrok
      run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok TCP Tunnel on Port 6080
      run: |
        ./ngrok tcp 6080 > ngrok.log &
        sleep 5
        echo "Waiting for ngrok to initialize..."
        until curl -s http://localhost:4040/api/tunnels | grep -q "tcp://"; do
          echo "Waiting..."
          sleep 2
        done
        echo "Ngrok tunnel started!"

    - name: Pull Android Docker Image
      run: docker pull butomo1989/docker-android-x86-9.0

    - name: Run Android Docker Container
      run: |
        docker run --privileged -d \
          -e DEVICE="Realme GT Master Edition" \
          -e WEB_VNC=true \
          -p 6080:6080 \
          --name kangwifi-android \
          butomo1989/docker-android-x86-9.0

    - name: Show Ngrok TCP Address
      run: |
        sleep 3
        curl -s http://localhost:4040/api/tunnels | grep -o 'tcp://[^"]*'

    - name: Keep Runner Alive
      run: tail -f /dev/null
