name: kangwifi-android-vnc

on: [workflow_dispatch]

jobs:
  run-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install dependencies & Ngrok
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl
        wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        mv ngrok /usr/local/bin/ngrok
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Pull Docker Android Image
      run: docker pull butomo1989/docker-android-x86-9.0

    - name: Run Android Docker Container
      run: |
        docker run --privileged -d \
          -e DEVICE="Realme GT Master Edition" \
          -e WEB_VNC=true \
          -p 6080:6080 \
          --name kangwifi-android \
          butomo1989/docker-android-x86-9.0

    - name: Start Ngrok Tunnel (Expose VNC)
      run: |
        ngrok tcp 6080 > ngrok.log &
        sleep 10

    - name: Display Ngrok VNC URL
      run: |
        for i in {1..20}; do
          ADDR=$(curl -s http://127.0.0.1:4040/api/tunnels | grep -o 'tcp://[^"]*')
          if [[ -n "$ADDR" ]]; then
            echo "VNC Available at: $ADDR"
            break
          fi
          echo "Waiting..."
          sleep 3
        done

    - name: Keep job alive
      run: tail -f /dev/null
