name: KangWiFi Android x86 Boot

on:
  workflow_dispatch:

jobs:
  boot-android:
    runs-on: ubuntu-latest
    name: Boot Android 13 x86 KangWiFi via QEMU with VNC

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-system-x86 curl unzip xvfb

      - name: Download Android x86 ISO
        run: |
          mkdir iso
          curl -L -o iso/android13.iso https://sourceforge.net/projects/android-x86/files/Release/android-x86_64-13.0.iso/download

      - name: Download and install ngrok
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok

      - name: Start ngrok tunnel (VNC)
        run: |
          ngrok config add-authtoken 2vWFHnFGqfIqtmrVs1Ltfc2OChV_6YN61Ge2uiRjV5a1WqdY4
          nohup ngrok tcp 5900 &
          sleep 10
          curl -s http://localhost:4040/api/tunnels > tunnels.json
          cat tunnels.json

      - name: Start Android x86 with QEMU
        run: |
          qemu-system-x86_64 \
            -m 2048 \
            -vga std \
            -smp 2 \
            -cdrom iso/android13.iso \
            -boot d \
            -net nic \
            -net user \
            -display vnc=:0 \
            -no-reboot \
            -rtc base=utc \
            -serial mon:stdio \
            -no-audio

      - name: Keep Runner Alive
        run: |
          echo "Android boot complete. VNC is live. Job will stay alive..."
          tail -f /dev/null
