name: Android VNC Remote - kangwifi

on: [push, workflow_dispatch]

jobs:
  android-vnc:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Setup dependencies
      run: |
        sudo apt update
        sudo apt install -y qemu-system-x86 unzip wget curl xz-utils net-tools

    - name: Download Android x86 ISO
      run: |
        wget -O android.iso https://github.com/chefstuff/android-vnc/releases/download/9.0-r2/android-x86_64-9.0-r2.iso

    - name: Download Ngrok
      run: |
        curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        chmod +x ngrok

    - name: Auth Ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok VNC Tunnel
      run: |
        nohup ./ngrok tcp 5900 > ngrok.log &
        sleep 3
        curl -s localhost:4040/api/tunnels > tunnels.json || true

    - name: Print Ngrok VNC Address
      run: |
        sleep 10
        curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[] | select(.proto=="tcp") | "VNC: \(.public_url)"'

    - name: Run Android QEMU VM
      run: |
        wget -O android.qcow2 https://github.com/chefstuff/android-vnc/releases/download/9.0-r2/android_disk.qcow2
        qemu-system-x86_64 \
          -m 2048 \
          -smp 2 \
          -machine accel=tcg \
          -name kangwifi \
          -net nic -net user \
          -device virtio-tablet-pci \
          -vnc :0 \
          -cdrom android.iso \
          -drive file=android.qcow2,format=qcow2 \
          -boot d \
          -enable-kvm || true

    - name: Keep Alive
      run: |
        while true; do sleep 300; done
