name: kangwifi-android-vnc

on: [workflow_dispatch]

jobs:
  run-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Ngrok
      run: |
        wget -q -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok.zip
        chmod +x ngrok
        mv ngrok /usr/local/bin/

    - name: Pull Docker Android Image
      run: docker pull butomo1989/docker-android-x86-9.0

    - name: Run Android Docker Container
      run: |
        docker run --privileged -d \
          -e DEVICE="Realme GT Master Edition" \
          -e WEB_VNC=true \
          -p 6080:6080 \
          --name kangwifi-android \
          butomo1989/docker-android-x86-9.0

    - name: Wait for VNC to be ready
      run: |
        echo "Waiting for VNC (port 6080) to be available..."
        for i in {1..30}; do
          if nc -z localhost 6080; then
            echo "VNC port is open!"
            break
          fi
          echo "Still waiting..."
          sleep 2
        done

    - name: Start Ngrok Tunnel for VNC
      run: |
        nohup ngrok http 6080 > ngrok.log 2>&1 &
        sleep 10
        curl -s http://127.0.0.1:4040/api/tunnels > tunnels.json || true
        cat tunnels.json

    - name: Show Ngrok Public URL
      run: |
        echo "Ngrok public VNC URL:"
        curl -s http://127.0.0.1:4040/api/tunnels | grep -o 'https://[^"]*'

    - name: Keep GitHub Actions job alive
      run: tail -f /dev/null
