name: kangwifi-android-vnc

on: [workflow_dispatch]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y tmux curl jq

    - name: Install Ngrok from official repo
      run: |
        curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update
        sudo apt install -y ngrok

    - name: Auth Ngrok
      run: ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Pull Docker Android
      run: docker pull butomo1989/docker-android-x86-9.0

    - name: Run Android Container
      run: |
        docker run --privileged -d \
          -e DEVICE="Realme GT Master" \
          -e WEB_VNC=true \
          -p 6080:6080 \
          --name kangwifi-android \
          butomo1989/docker-android-x86-9.0

    - name: Start Ngrok in tmux session
      run: |
        tmux new-session -d -s ngrok 'ngrok http 6080'
        sleep 10

    - name: Get Ngrok Public URL
      run: |
        echo "Waiting for ngrok to initialize..."
        for i in {1..20}; do
          NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          if [[ "$NGROK_URL" == https* ]]; then
            echo "Ngrok VNC URL: $NGROK_URL"
            echo "::set-output name=vnc_url::$NGROK_URL"
            break
          fi
          echo "Still waiting for ngrok..."
          sleep 2
        done

    - name: Keep job alive
      run: tail -f /dev/null
